export const Errors = Object.freeze({
  AccessPointNotExistent: 'AccessPointNotExistent',
  AccessPointAlreadyExists: 'AccessPointAlreadyExists',
  AccessPointScoreCannotBeLower: 'AccessPointScoreCannotBeLower',
  MustBeAccessPointOwner: 'MustBeAccessPointOwner',
  MustHaveCollectionRole: 'MustHaveCollectionRole',
  MustHaveTokenRole: 'MustHaveTokenRole',
  MustHaveAtLeastOneOwner: 'MustHaveAtLeastOneOwner',
  RoleAlreadySet: 'RoleAlreadySet',
  MustBeTokenOwner: 'MustBeTokenOwner',
  ContractIsPaused: 'ContractIsPaused',
  ContractIsNotPaused: 'ContractIsNotPaused',
  ContractIsNotPausable: 'ContractIsNotPausable',
  PausableIsSetTo: 'PausableIsSetTo',
  ThereIsNoTokenMinted: 'ThereIsNoTokenMinted',
  RequiredPayment: 'RequiredPayment',
});
