service: nfa-serverless
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  timeout: 150
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prd'}
  region: ${opt:region, 'us-west-2'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    DEBUG: '*'
    AWS_STAGE: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  httpApi:
    cors:
      allowedOrigins: '*'
      headers: '*'
      allowedMethods:
        - POST
      allowCredentials: false
      maxAge: 6000 # In seconds

layers:
  TopicAwsNodeModules:
    path: lambda-layers-node_modules
  TopicAwsLibs:
    path: lambda-layers-libs
  TopicPrismaAwsPrismaClient:
    path: lambda-layers-prisma-client

package:
  {
    patterns:
      [
        'dist/**/*.prisma',
        '**/libquery_engine-rhel-openssl-1.0.x.so.node',
        'dist/serverless/.env',
        '!node_modules/**',
      ],
  }

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - 'aws-sdk'
    target: 'node18'
    platform: 'node'
    concurrency: 10

functions:
  submitBuildInfo:
    # Deployment:
    handler: ./dist/src/functions/builds/handler.submitBuildInfo # TODO This will not work, need to change to nfa-serverless/dist/serverless/src/functions/builds/handler.submitBuildInfo
    # Local development:
    # handler: ./src/functions/builds/handler.submitBuildInfo
    events:
      - http:
          path: build
          method: post
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
    environment:
      NODE_ENV: production
    layers:
      - { Ref: TopicAwsNodeModulesLambdaLayer }
      - { Ref: TopicAwsLibsLambdaLayer }
      - { Ref: TopicPrismaAwsPrismaClientLambdaLayer }

  submitNFA:
    # Deployment:
    handler: ./dist/src/functions/mints/handler.submitNFA # TODO This will not work, need to change to nfa-serverless/dist/serverless/src/functions/mints/handler.submitMintInfo
    # Local development:
    # handler: ./src/functions/mints/handler.submitMintInfo
    events:
      - http:
          path: submitNFA
          method: post
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
    environment:
      NODE_ENV: production
    layers:
      - { Ref: TopicAwsNodeModulesLambdaLayer }
      - { Ref: TopicAwsLibsLambdaLayer }
      - { Ref: TopicPrismaAwsPrismaClientLambdaLayer }