# .graphclientrc.yml
sources:
  - name: FleekNFA
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/emperororokusaki/flk-test-subgraph #replace for nfa subgraph
  - name: ENS
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens

documents:
  - ./graphql/*.graphql

