# .graphclientrc.yml
sources:
  - name: FleekNFA
    handler:
      graphql:
        # QA NET
        endpoint: http://ec2-34-215-155-25.us-west-2.compute.amazonaws.com:8000/subgraphs/name/FleekNFA
      #  endpoint: https://api.thegraph.com/subgraphs/name/emperororokusaki/second-test-subgraph

  - name: ENS
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens
    transforms:
      - rename:
          - from:
              type: Transfer
            to:
              type: ENSTransfer

documents:
  - ./graphql/*.graphql

